`WF2` improvements
OpenFn/openfn-lime pull request #15
Opened 2023-06-01 14:37 UTC by mtuchi

### Summary
This PR tries to address @josephjclark feedback comment from the previous PR 👉🏽 https://github.com/OpenFn/openfn-lime/pull/5

I have also updated the `jobs/wf2-4-getOclMap.js` job  to use the `OCL` adaptor, This will fix #7

2023-06-01 15:15 UTC, mtuchi commented
@josephjclark please have a look, i have implemented your feedback on #5

2023-06-02 07:39 UTC, josephjclark requested changes
This looks much better, and it's a nice approach using the `fn` to map your queries first. You could do this with an each but I'm really nitpicking at that point 😅

I see one possible major issue on `patientsMapping`.

I've suggested some restyling of some of your lookups. This is cosmetic. You don't have to use those but I think they're a bit nicer?

2023-06-02 07:39 UTC, josephjclark commented on jobs/wf2-2-upsertTEIs.js
> +fn(state => {
I wasn't expecting the use of `fn` here - but it does give you a nice clean each/upsert later on!

2023-06-02 07:39 UTC, josephjclark commented on jobs/wf2-2-upsertTEIs.js
> +  'patients[*]',
Shouldn't this be `each('patientsMapping[*]'...)` ?

2023-06-02 07:39 UTC, josephjclark commented on jobs/wf2-2-upsertTEIs.js
> +    const identifier = oldId ? oldId.identifier : openMRSID.identifier;
This is looking better. But looking again this mornig I can't help but think this is a lot simpler and easier to read if you do:
```
const DHIS2_PATIENT_NUMBER='8d79403a-c2cc-11de-8d13-0010c6dffd0f'
const OPENMRS_AUTO_ID='05a29f94-c0ed-11e2-94be-8c13b969e334'

const identifier = patient.identifiers.find(i => i.identifierType.uuid === DHIS2_PATIENT_NUMBER) ||  
   patient.identifiers.find(i => i.identifierType.uuid === OPENMRS_AUTO_ID)
```
The `find` syntax is so simple and clean I really don't think it's worth aliasing, and the uses of constants makes the code a bit easier to read without the need for comments,

2023-06-02 07:39 UTC, josephjclark commented on jobs/wf2-2-upsertTEIs.js
> +  'patients[*]',
And rather than call it `patientsMapping`, which is kinda meaningless, maybe call it `patientsUpsert` or `teiUpsert` or something a bit richer

2023-06-02 07:39 UTC, josephjclark commented on jobs/wf2-4-getOclMap.js
> +    query: {
Oh yes, that's much nicer - good idea!

2023-06-02 07:39 UTC, josephjclark commented on jobs/wf2-5-createEvents.js
> +    state => ({
Beautiful 😘👌

2023-06-02 07:39 UTC, josephjclark commented on jobs/wf2-5-createEvents.js
> +    const valueForEncounter2 = oclMap2 ? oclMap2.to_concept_name_resolved : '';
This is much less important, but a few things about this bother me.

What do you think about using this pattern instead? This is untested and I'm not sure the variable names are right...
```
    const conceptIds = [
      'da33d74e-33b3-495a-9d7c-aa00a-aa0160',
      'da33d74e-33b3-495a-9d7c-aa00a-aa0177',
    ];
    const [valueForEncounter1, valueForEncounter2] = conceptIds.map(id => {
      const obs = data.obs.find(ob => ob.concept.uuid === id);
      if (obs) {
        const ocl = oclMappings.find(
          ocl => ocl.from_concept_name_resolved === obs.value.display
        );
        if (ocl) {
          return ocl.to_concept_name_resolved;
        }
      }
      return '';
    });
    ```

2023-06-07 08:47 UTC, josephjclark commented on jobs/wf1-2-createPatients.js
> +fn(state => ({ ...state, data: {}, references: [] }));
I've just noticed that there are a couple of operations in this file that need the `(state)` wrapper removing (the each/post on line 35, the each/createPatient on line 106)

2023-06-07 16:09 UTC, josephjclark commented on jobs/wf2-5-createEvents.js
> +    const valueForEncounter2 = oclMap2 ? oclMap2.to_concept_name_resolved : '';
Actually don't worry about this - when we improve the ocl adaptor we can come back and revisit this algorithm.

2023-06-07 17:14 UTC, closed without merging